In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Pandas

In [2]:
#Import pandas and numpy
import pandas as pd # used for mathematical computation # built on top of numpy
import numpy as np

Data stractures used in pandas
1. pandas series
2. pandas data Frame

In [3]:
#issue with list # try  a list with a scaler value
list1 =[1,2,3,4]

list1* 4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
#create a series and multiply the values with a scaler value
s1= pd.Series ([1,2,3,4])
type(s1)
# multiply series with a scaler value
s1* 4

0     4
1     8
2    12
3    16
dtype: int64

In [5]:
# Try categorical series
s2= [("car", 4),("boat", 10),("bike", 2)]
type(s2)

list

In [6]:
#convert a list to a dataframe
df=pd.DataFrame(s2, columns= ["items", "price"])
df

  items  price
0   car      4
1  boat     10
2  bike      2

In [7]:
#checking/proving dataframe is combination of series
type(df)

pandas.core.frame.DataFrame

In [8]:
type(df["items"])

pandas.core.series.Series

## Reading from files

In [9]:
import pandas as pd
import numpy as np

In [10]:
%pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\ADMIN\Documents\fs_essentials_course\essentials_env\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\ADMIN\Documents\fs_essentials_course\essentials_env\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
#Loading the dataset #excel dataset, sample super store dataset
df = pd.read_excel("Sample_Superstore.xlsx")
df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Writing to files

In [12]:
#saving the file to csv # use to_csv() and set index = False
df.to_csv("sample_clean.csv", index= None)
df_csv= pd.read_csv("sample_clean.csv")
df_csv

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

## Dataframe basics

In [13]:
#setting the default data view # pd.set_option("display.max_columns", 500)
pd.set_option("display.max_columns", 500)
df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [14]:
#Displaying the top 3 rows # use head()
df.head(3)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523

In [15]:
#Displaying the last 3 rows # use tail()
df.tail()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [16]:
#Displaying 3 random rows #use sample()
df.sample(3, random_state= 41)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
7488,22197,Critical,0.01,26.31,5.89,2731,Robert Sloan,Regular Air,Consumer,Technology,Computer Peripherals,Small Box,"Micro Innovations Micro 3000 Keyboard, Black",0.75,West,Washington,Bremerton,98310,2012-07-14,2012-07-15,-75.380,12,317.71,88120
7602,19110,Not Specified,0.03,55.99,5.00,2778,Alison Jones,Regular Air,Consumer,Technology,Telephones and Communication,Small Pack,Accessory6,0.80,South,North Carolina,Wilmington,28403,2012-06-26,2012-06-27,310.218,7,337.93,87170
7757,18419,Medium,0.05,15.68,3.73,2840,Bob Berg,Regular Air,Corporate,Furniture,Office Furnishings,Small Pack,Artistic Insta-Plaque,0.46,South,Florida,North Miami,33161,2010-12-11,2010-12-13,1166.628,17,260.01,87885

In [17]:
#checking the columns # use columns attribute
df.columns.tolist()

['Row ID',
 'Order Priority',
 'Discount',
 'Unit Price',
 'Shipping Cost',
 'Customer ID',
 'Customer Name',
 'Ship Mode',
 'Customer Segment',
 'Product Category',
 'Product Sub-Category',
 'Product Container',
 'Product Name',
 'Product Base Margin',
 'Region',
 'State or Province',
 'City',
 'Postal Code',
 'Order Date',
 'Ship Date',
 'Profit',
 'Quantity ordered new',
 'Sales',
 'Order ID']

In [18]:
#checking the index # use df.index
df.index

RangeIndex(start=0, stop=9426, step=1)

## Dataframe summary

In [19]:
#Checking the data Summary # use info(), we can also use info(verbose=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

Observation: the data contains 2 datetime, 11 numeric and 11 categorical columns

In [20]:
df.dtypes

Row ID                           int64
Order Priority                  object
Discount                       float64
Unit Price                     float64
Shipping Cost                  float64
Customer ID                      int64
Customer Name                   object
Ship Mode                       object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Container               object
Product Name                    object
Product Base Margin            float64
Region                          object
State or Province               object
City                            object
Postal Code                      int64
Order Date              datetime64[ns]
Ship Date               datetime64[ns]
Profit                         float64
Quantity ordered new             int64
Sales                          float64
Order ID                         int64
dtype: object

In [21]:
#Checking concise Descriptive statistics for numerical variables# use df.describe()
df.describe ().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9426.0,20241.015277,2.0,19330.25,21686.5,24042.75,26399.0,6101.890965
Discount,9426.0,0.049628,0.0,0.02,0.05,0.08,0.25,0.031798
Unit Price,9426.0,88.303686,0.99,6.48,20.99,85.99,6783.02,281.540982
Shipping Cost,9426.0,12.795142,0.49,3.1925,6.05,13.99,164.73,17.181203
Customer ID,9426.0,1738.422236,2.0,898.0,1750.0,2578.75,3403.0,979.167197
Product Base Margin,9354.0,0.512189,0.35,0.38,0.52,0.59,0.85,0.135229
Postal Code,9426.0,52446.327286,1001.0,29406.0,52302.0,78516.0,99362.0,29374.597802
Order Date,9426,2012-03-05 18:33:59.465308672,2010-01-01 00:00:00,2011-03-07 06:00:00,2012-04-08 00:00:00,2013-03-26 00:00:00,2013-12-31 00:00:00,NaN
Ship Date,9426,2012-03-07 19:16:18.485041408,2010-01-02 00:00:00,2011-03-09 00:00:00,2012-04-09 00:00:00,2013-03-28 00:00:00,2014-01-17 00:00:00,NaN
Profit,9426.0,139.23641,-16476.838,-74.017375,2.5676,140.24385,16332.414,998.486483
Quantity ordered new,9426.0,13.79843,1.0,5.0,10.0,17.0,170.0,15.107688
Sales,9426.0,949.706272,1.32,61.2825,203.455,776.4025,100119.16,2598.019818
Order ID,9426.0,82318.489073,6.0,86737.25,88344.5,89987.75,91591.0,19149.448857

In [22]:
#Checking concise Descriptive statistics for categorical variables# use df['col'].describe()
df.describe (include= "O").T # use capital O or object

,count,unique,top,freq
Order Priority,9426,6,High,1970
Customer Name,9426,2703,Louis Parrish,27
Ship Mode,9426,3,Regular Air,7036
Customer Segment,9426,4,Corporate,3375
Product Category,9426,3,Office Supplies,5181
Product Sub-Category,9426,17,Paper,1379
Product Container,9426,7,Small Box,4887
Product Name,9426,1263,"Global High-Back Leather Tilter, Burgundy",27
Region,9426,4,Central,2899
State or Province,9426,49,California,1021
City,9426,1424,New York City,202

In [23]:
#checking
df.shape
print(f"my dataset has {df.shape[0]} rows and {df.shape[1]} columns")

my dataset has 9426 rows and 24 columns

## Subsetting Columns

This is the act of selecting  a few columns from the entire dataframe.

In [24]:
#selcting the specific columns# use df[['col1', 'col2', 'col3']] e.g. selsct Order Date, Product Date, and ship mode
# when we select a column using single [] output will be a series
df.columns.tolist()

['Row ID',
 'Order Priority',
 'Discount',
 'Unit Price',
 'Shipping Cost',
 'Customer ID',
 'Customer Name',
 'Ship Mode',
 'Customer Segment',
 'Product Category',
 'Product Sub-Category',
 'Product Container',
 'Product Name',
 'Product Base Margin',
 'Region',
 'State or Province',
 'City',
 'Postal Code',
 'Order Date',
 'Ship Date',
 'Profit',
 'Quantity ordered new',
 'Sales',
 'Order ID']

In [25]:
cs= df["Customer Name"]
cs

0       Janice Fletcher
1         Bonnie Potter
2         Bonnie Potter
3         Bonnie Potter
4         Bonnie Potter
             ...
9421     Frederick Cole
9422     Frederick Cole
9423     Frederick Cole
9424      Tammy Buckley
9425      Tammy Buckley
Name: Customer Name, Length: 9426, dtype: object

In [26]:
#Convert the above to a df
cs= df[["Customer Name"]]
cs

        Customer Name
0     Janice Fletcher
1       Bonnie Potter
2       Bonnie Potter
3       Bonnie Potter
4       Bonnie Potter
...               ...
9421   Frederick Cole
9422   Frederick Cole
9423   Frederick Cole
9424    Tammy Buckley
9425    Tammy Buckley

[9426 rows x 1 columns]

In [27]:
# to make a single column a dataframe we use double [[]]
df_3coln=df[['Discount', 'Unit Price', 'Shipping Cost']]
df_3coln.head(5)

   Discount  Unit Price  Shipping Cost
0      0.01        2.88           0.50
1      0.01        2.84           0.93
2      0.03        6.68           6.15
3      0.01        5.68           3.60
4      0.00      205.99           2.50

In [28]:
#selecting a few cloumns
df[2:6]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.6400,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.5100,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.2023,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 194,0.37,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.0523,37,2011.67,88524

In [29]:
# we can use slicing as well e.g. df[df.columns[1:5]]df
df[df.columns[:5]]

      Row ID Order Priority  Discount  Unit Price  Shipping Cost
0      18606  Not Specified      0.01        2.88           0.50
1      20847           High      0.01        2.84           0.93
2      23086  Not Specified      0.03        6.68           6.15
3      23087  Not Specified      0.01        5.68           3.60
4      23088  Not Specified      0.00      205.99           2.50
...      ...            ...       ...         ...            ...
9421   20275       Critical      0.06       35.89          14.72
9422   20276       Critical      0.00        3.34           7.49
9423   24491  Not Specified      0.08      550.98          45.70
9424   25914           High      0.10      105.98          13.99
9425   24492  Not Specified      0.09        7.78           2.50

[9426 rows x 5 columns]

In [30]:
#for loop on a list
fruits = ["banana", "orange", "kiwi"]
for fruit in fruits:
    print(fruit)

banana
orange
kiwi

In [31]:
#list comprehension
#[fruit[:3] for fruit in fruits if fruit == "orange"]
[fruit[1:4] for fruit in fruits if fruit == "orange"]

['ran']

In [32]:
#Using list comprehnsion e.g df[[c for c in df.columns]]
df[[c for c in df.columns][:4]]

      Row ID Order Priority  Discount  Unit Price
0      18606  Not Specified      0.01        2.88
1      20847           High      0.01        2.84
2      23086  Not Specified      0.03        6.68
3      23087  Not Specified      0.01        5.68
4      23088  Not Specified      0.00      205.99
...      ...            ...       ...         ...
9421   20275       Critical      0.06       35.89
9422   20276       Critical      0.00        3.34
9423   24491  Not Specified      0.08      550.98
9424   25914           High      0.10      105.98
9425   24492  Not Specified      0.09        7.78

[9426 rows x 4 columns]

## Select dtypes

In [33]:
# Selecting the numerical variables use df.select_dtypes(), include what you want to select as an argument
# you can change int to object and rerun the code... we use include number as well
df.select_dtypes(float)[:6]

,Discount,Unit Price,Shipping Cost,Product Base Margin,Profit,Sales
0,0.01,2.88,0.50,0.36,1.3200,5.90
1,0.01,2.84,0.93,0.54,4.5600,13.01
2,0.03,6.68,6.15,0.37,-47.6400,49.92
3,0.01,5.68,3.60,0.56,-30.5100,41.64
4,0.00,205.99,2.50,0.59,998.2023,1446.67
5,0.09,55.48,14.30,0.37,1388.0523,2011.67

## Select as series vs dataframe

In [34]:
#checking the series, use df['Col name']

In [35]:
#making the above as a dataframe , use df[['col name']]

## loc and iloc

We can use loc(variable location), and iloc(index location) to access the variables as well

### iloc

In [36]:
# getting the value using iloc e.g df.iloc[1, 1]

In [37]:
#slicing e.g df.iloc[:5, :5]

In [38]:
#Getting specific row e.g df.iloc[5], we can present our result in dataframe formart as well

In [39]:
#Checking the index 1 columns e.g df.iloc[:, 1]

In [40]:
#getting index 1 and 2 columns, e.g  df.iloc[:, [1, 2]]

Loc

we use loc when we want to select the variable by the name

In [41]:
#subsetting  2 columns df.loc[:, ['col1', 'col2']]

#### loc filter expressions

we can use loc filter to get specific records

In [42]:
#Get the records of a specific value e.g  df.loc[df['Region'] == 'West']
df.Region.unique()

array(['Central', 'West', 'East', 'South'], dtype=object)

In [43]:
# sales above 50

In [44]:
#we can use loc to get records of more than one specific variables

In [45]:
#we can use tilde(~) to get the records of those not represented in the code
#df1.loc[~((df1['Product Category'] == 'Furniture') & (df1['Order Date'] == '2010-07-07'))]

## query

Query method is another way of getting specific records

In [46]:
#?df1.query
df1= df.copy(deep=True)
df1

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,Labels,Small Box,Avery 49,0.36,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Pens & Art Supplies,Wrap Bag,SANFORD Liquid Accent™ Tank-Style Highlighters,0.54,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 1968,0.37,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Small Pack,Acme® Preferred Stainless Steel Scissors,0.56,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Pens & Art Supplies,Wrap Bag,"Eldon Spacemaker® Box, Quick-Snap Lid, Clear",0.54,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,Envelopes,Small Box,Staples #10 Colored Envelopes,0.38,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [47]:
#getting specific records e.g df.query('Sales >200 and Region == "West"')
df[df["Sales"] >200]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 194,0.37,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,Office Machines,Jumbo Drum,Canon S750 Color Inkjet Printer,0.38,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,Chairs & Chairmats,Jumbo Drum,Global Troy™ Executive Leather Low-Back Tilter,0.60,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,Appliances,Small Box,Kensington 6 Outlet MasterPiece® HOMEOFFICE Po...,0.56,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.467300,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,Telephones and Communication,Small Pack,Accessory23,0.36,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.481500,19,596.35,87549
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bush Advantage Collection® Round Conference Table,0.64,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [48]:
df.query("Sales >200")

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,Product Sub-Category,Product Container,Product Name,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,Telephones and Communication,Small Box,V70,0.59,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,Paper,Small Box,Xerox 194,0.37,West,Washington,Anacortes,98221,2011-11-09,2011-11-11,1388.052300,37,2011.67,88524
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,Office Machines,Jumbo Drum,Canon S750 Color Inkjet Printer,0.38,West,Washington,Anacortes,98221,2013-07-01,2013-07-08,1001.445300,12,1451.37,88526
7,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,Chairs & Chairmats,Jumbo Drum,Global Troy™ Executive Leather Low-Back Tilter,0.60,West,California,San Gabriel,91776,2010-12-13,2010-12-15,4390.366500,12,6362.85,90193
9,24782,High,0.01,90.24,0.99,6,Dwight Hwang,Regular Air,Home Office,Office Supplies,Appliances,Small Box,Kensington 6 Outlet MasterPiece® HOMEOFFICE Po...,0.56,West,California,San Jose,95123,2011-05-26,2011-05-26,1045.467300,16,1515.17,90194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,Telephones and Communication,Small Pack,Accessory23,0.36,East,West Virginia,Fairmont,26554,2013-10-04,2013-10-05,411.481500,19,596.35,87549
9420,18329,High,0.08,212.60,52.20,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Bush Advantage Collection® Round Conference Table,0.64,East,West Virginia,Charleston,25314,2011-04-12,2011-04-12,-513.790420,10,1969.31,87531
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,Envelopes,Small Box,Jet-Pak Recycled Peel 'N' Seal Padded Mailers,0.40,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,Tables,Jumbo Box,Chromcraft Bull-Nose Wood Oval Conference Tabl...,0.71,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,Office Furnishings,Medium Box,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",0.65,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530

In [49]:
#Another different way of using query method
#min_sale = 600
#df.query('Sales > @min_Sale and (Region == "West")')
#----------------------------------------------

## Summary Statistics

This is when we want to infer or get more information on the variable performance

In [50]:
#we can use min, max, mean, std, and quantile

## agg

This is used when we need to get summary statistics of more than 1 at ago.

In [51]:
# Getting  min, mean, max of 3 variables('Sales','Discount', 'Profit'), use  df[['col1','col2', 'col3']].agg(['mean', 'min', 'max'])

In [52]:
#another way of doing the above
'''
df1[['Sales','Discount', 'Profit']].agg(
    {
        'Sales': ['min', 'max'],
        'Discount': ['mean'],
        'Profit': ['min', 'max']
    }
)
'''

"\ndf1[['Sales','Discount', 'Profit']].agg(\n    {\n        'Sales': ['min', 'max'],\n        'Discount': ['mean'],\n        'Profit': ['min', 'max']\n    }\n)\n"

## Summarize categoricals

we use different way to categorize categorical variables

In [53]:
#use unique to see the unique values in the variable, use  df['col'].unique()

In [54]:
#nunique is used to get the number, use  df['col'].nunique()

In [55]:
#Value count is used to get the number of occurances use df['col'].value_counts()

In [56]:
# valuse counts for 2 variable, return dataframe  df[['col1', 'col2']].value_counts()

In [57]:
# we use reset index so that the result starts from index zero use df[['col1', 'col2']].value_counts().reset_index()

## shift, cumsum

In [58]:
#shift is commonly used in time series , use df[['col']].shift(1)
#df['_sales'] = df[['Sales']].shift(1)

In [59]:
#shift last value df[['col']].shift(-1)
#df[['Sales']].shift(-1)

In [60]:
#fill up the shitfed value, use df[['col']].shift(3, fill_value=100)
#df[['Sales']].shift(1, fill_value= 00)

In [61]:
#summing up the sum values, use df[['col']].cumsum()
#df[['Sales']].cumsum()

In [62]:
#we can also do cummax, and cummin

## Rolling methods

In [63]:
#using Rolling, usse df[['col']].rolling(window=5).mean()
#df[['Sales']].rolling(window=3).mean()

## Groupby

This is used when we want to summarize categorical features based on a certain numerical variable

In [64]:
# use groupby, use df.groupby('cat_col')[['num_coll']].mean(), e.g region and sales

In [65]:
#Using agg() together with groupby e.g df.groupby('cta_col')[['num_col']].agg(['mean', 'min', 'max'])

In [66]:
#combining two numerical columns

## New columns

In [67]:
#ctreating a new column,  e.g df['new_col'] = df['Sales'] - df['Profit']

In [68]:
#Another way of creating new column using assign method, use df=df.assign(colname=expression)
#creating new column using .assign()
#df1=df1.assign(col_2=df["Profit"]/0.3)

## Sorting

This is a way of ordering the values either in ascending or descending order

In [69]:
#sort values use  df.sort_values('col'), we can apply argument ascending= False to get the result in descending order

In [70]:
#resetting the index, use df[['col1', 'col2', 'col3']].sort_values('col3', ascending=False).reset_index(drop=True)

## Missing data

This is how we can check and fix null values

In [89]:
#checking missing values, use df.isna(), add .sum()a better result
df[df.isna().sum()]

KeyError: "None of [Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n       0],\n      dtype='int64')] are in the [columns]"

In [72]:
#fixing the null values  by dropping the rows df.dropna(subset=['col with missing value']), or just df.dropna() for entire dataframe

In [73]:
#filling up the missing value with specific value, use df[['col1', 'col2', 'col3']].fillna(0)

In [74]:
#Filling with the mean of the column, use df['col1'].fillna(df['col1'].mean())

## Concat

concat is used when all the variables as similar

In [75]:
# create 2 dataframe
#df2 = df1.query('Region == "West"').copy()
#df3 = df1.query('Region == "East"').copy()

In [76]:
#concat, use pd.concat([df1, df2])

In [77]:
#we can resset the index then concat as well
#df1 = df1.reset_index(drop=True)
#df2 = df2.reset_index(drop=True)

In [78]:
#concat, use pd.concat([df1, df2], axis=1)
#df_concat=pd.concat([df1,df2], axis=1)
#df_concat.head()

## Merge dataframes

In [79]:
#create 2 dataframe
#dfm1 = df1.groupby(['Region', 'Order Date'])[['Sales']].mean().reset_index()
#dfm2 = df1.groupby(['Region', 'Order Date'])[['Profit']].mean().reset_index()

In [80]:
#merge left, use df1.merge(df2, how="left")
#dfm1.merge(dfm2,how='left')

In [81]:
#merge on right, use df1.merge(df2, how="right")

In [82]:
#merging on outer, use df1.merge(df2, how="outer")

## Merge suffixes

In [83]:
#merging using suffices use,
#pd.merge(dfm1, dfm2, on=['id', 's_id'])

In [84]:
#merge on specific similar column use
#pd.merge(df1, df2, on=df['col1'])

In [85]:
#merging using both letf and right on,use
#pd.merge(df1, df2, left_on=['col1'], right_on=['col1'])

## Do research on pivot table.